version: '3.8'

services:
  mysql:
    container_name: todo_db
    image: mysql:8.0.31
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootkey
      MYSQL_DATABASE: db
  phpmyadmin:
    container_name: todo_pma
    image: phpmyadmin:5.2.0-apache
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: mysqlrootkey
      MEMORY_LIMIT: -1
      UPLOAD_LIMIT: 4096M
    depends_on:
      - mysql
  laravel-app:
    image: elkynerojas/laravel:10
    container_name: todo_app
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - phpmyadmin
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: elkynerojas/nuxt-node:16
    container_name: todo_node
    command: sh -c 'npm install && npm run watch'
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/nuxt-app
